source: camera
# source: video2.mp4
device: "IAC Driver Bus 1"
# device: "H4MIDI-WC Port 1"
# device: "S-1 MIDI IN"

triggers:
  
  - name: "1"
    position:
      x: 10
      y: 15
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 0
  
  - name: "2"
    position:
      x: 10
      y: 40
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 1
  
  - name: "3"
    position:
      x: 10
      y: 70
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 2
  
  - name: "4"
    position:
      x: 75
      y: 15
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 3
  
  - name: "5"
    position:
      x: 75
      y: 40
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 4
  
  - name: "6"
    position:
      x: 75
      y: 70
      width: 15
      height: 15
    type: "difference"
    threshold: 10  # Average pixel difference
    debounce: 0.1
    throttle: 0.2
    midi:
      note: 1  # E
      velocity:
        min: [10, 80]
        max: [20, 127]
      channel: 5
  
  - name: "Range Trigger"
    position:
      x: 10
      y: 70
      width: 10
      height: 30
    type: "range"
    min: 0
    max: 255
    midi:
      cc: 25
      channel: 0