# source: camera
source: video2.mp4
# device: "IAC Driver Bus 1"
device: "S-1 MIDI IN"

triggers:
  - name: "A"
    position:
      x: 80
      y: 10
      width: 10
      height: 10
    type: "brightness"
    threshold: 100
    midi:
      note: 64  # Middle C
      velocity: 100
      channel: 0
  
  - name: "B"
    position:
      x: 80
      y: 40
      width: 10
      height: 10
    type: "brightness"
    threshold: 120
    midi:
      note: 62  # D
      velocity: 100
      channel: 0
  
  - name: "C"
    position:
      x: 80
      y: 70
      width: 10
      height: 10
    type: "brightness"
    threshold: 120
    midi:
      note: 60  # E
      velocity: 100
      channel: 0

  - name: "Range Trigger"
    position:
      x: 10
      y: 70
      width: 10
      height: 30
    type: "range"
    min: 180
    max: 100
    midi:
      cc: 25
      channel: 0