source: "camera"

camera:
  width: 640
  height: 480
  fps: 30

triggers:
  - name: "Difference Trigger"
    position:
      x: 40
      y: 40
      width: 20
      height: 20
    type: "difference"
    threshold: 10  # Average pixel difference threshold (0-255)
    midi:
      note: 60  # Middle C
      velocity: 100
      channel: 0
