source: https://www.youtube.com/watch?v=oNHs_-pHZTs
overlay: [0, 80, 120, 20]

triggers:
  - name: ""
    colour:
      - [125, 255, 255, 30] # not active colour
      - [255, 0, 0, 180] # active colour
    shape:
      - [0, 15]
      - [100, 15]
    type: "brightness"
    threshold: 40
    retrigger:
      threshold: 80
      debounce: 0.5
    movement:
      direction: [0, 1]
      speed: 0.7
      duration: 40
      type: ping-pong
    midi:
      note: [42, 55, 58, 60, 62, 64, 66, 69, 91] 
      velocity:
        min: [40, 10]
        max: [150, 127]
      channel: 0
