source: https://www.youtube.com/watch?v=bCWc2ubxf2E

triggers:
  - name: "scan"
    colour:
      - [20, 60, 70]
      - [50, 255, 90]
    shape:
      - [0, 25]
      - [100, 25]
    type: "brightness"
    persist: 1
    threshold: 40
    retrigger:
      threshold: 80
      debounce: 0.5
    movement:
      direction: [0, 1]
      speed: 0.7
      duration: 40
      type: ping-pong
      random-start-points: true
    midi:
      note: [50, 54, 57, 64, 66, 69, 74] 
      velocity:
        min: [40, 10]
        max: [150, 127]
      channel: 0
